### ISSUE TITLE
Campos obligatorios en stop_times.txt

### ISSUE THREAD

**Issue by dachafra** [emtpalma/Open-Data#1]
El arrival_time, departure_time, stop_id y stop_sequence son campos obligatorios según la referencia oficial (https://developers.google.com/transit/gtfs/reference?hl=es-419#stop_times_fields) y en el archivo muchos de estos campos se encuentran vacíos.

**Comment by emtpalma** [comment]
Hola David
Nosotros trabajamos con frecuencias. Si revisas la definición de los ficheros, podrás ver que en de frecuencias, pone lo siguiente:
"Esta tabla tiene como objetivo representar horarios que **no tienen una lista fija de horas de parada**. Al definir los viajes en el archivo frequencies.txt, la persona que planifica el viaje ignora los valores absolutos de los campos arrival_time y departure_time de los viajes incluidos en stop_times.txt. En su lugar, la tabla stop_times define la secuencia de paradas y la diferencia de tiempo entre cada una de ellas."

**Comment by emtpalma** [comment]
Aunque es cierto que trabajamos en poder poner un número mayor de referencias de paso en el fichero stop_times, ya que esto permite mayor precisión en los resultados, no es obligatorio su uso en todos los registros. Únicamente en el primero y el último de cada "trip".
saludos

**Comment by dachafra** [comment]
Muchas gracias por la aclaración, tenemos que mejorar nuestro proceso de generación de los datos para que tenga en cuenta las frecuencias y no sólo el archivo de stop_times. Un saludo
