### ISSUE TITLE
Faltan líneas

### ISSUE THREAD

**Issue by gsabater** [emtpalma/Open-Data#2]
En `routes.txt` faltan lineas: L21, L1, L2, L9, etc...
Saludos

**Comment by emtpalma** [comment]
Quizá hubiera un fallo en el feed de septiembre. Esperamos haberlo solventado. Es conveniente revisar la web, ya que ahora mismo, algunas líneas se ofrecen bajo servicio a la demanda: https://pujaalbus.org/tad/, y por tanto no aparecen en el feed.
